### ISSUE TITLE
AttributeError: 'MS-CMRLoader' object has no attribute 'load_all_modalities_concatenated'

### ISSUE THREAD

**Issue by lconet** [agis85/multimodal_segmentation#8]
Can you share the loader for MS-CMR dataset that you have published your paper? Your paper has the cardiac dataset however this repository shows for 'CHAOS' dataset.

**Comment by agis85** [comment]
The cardiac dataset used in the paper is not public and therefore the loader is not uploaded. If the data ever gets released, then I will also publish the loader.
